### ISSUE TITLE
Pendings

### ISSUE THREAD

**Issue by apolo88** [Fielo-Plugins/fielocms-fieloprp#12]
- Review detail parameter for my invoices and invoice items ✅
- Create formula on invoice detail to get product name and replace the lookup ✅
- Upload invoice form (review with sebastian next steps) ✅
	- Initial status "New" for new invoices ✅ (done by the API)
	- Create checkbox on component object to set if the invoices will be upload with details or not. ✅
- Create two different page models (with details and without details) ✅

**Comment by tibeal** [comment]
**Pendings II**

- Create Custom Setting to store the Product Lookup Field of the Invoice Items (for implementations that are not going to use the standard Product2 object)
- Remove the calculations if the 3 fields are not present in the Frontend (Quantity, Unit Price and Total Price);
