### ISSUE TITLE
Invoice Upload: Submit Mode = Close does not seem to pass through Promotion analysis

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#19]
Program setting: 
Request Invoice Authorization = false

Active Promotion with the following rule: 
Invoice status equals to Approved and gives Fixed Value points equal to 100

CMS Invoice Upload setting:
Submit Mode = Close

After submitting the invoice from the CMS site, it was correctly Approved, without showing the error described in issue #6, which suggests that it's not passing through rule analysis stage.

Test Org: https://login.salesforce.com/?pw=fielo123&un=prpcms@plugin.com

**Comment by tibeal** [comment]
This Issue is due to the Prefix issue from Rule Engine. I'll open one issue at the fieloplt repo.
