### ISSUE TITLE
Invoice Upload: Submit button does not work when invoice doesn't have details

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#20]
Set the option *Has Details* to "false" in the Invoice Upload component.
Go to the Invoice Upload page at CMS, fill in the fields and press Submit.
No action occurs.
It doesn't matter if the program is set to have products or not. In both cases, the Submit button does not work when setting Has Details to false in the Invoice Upload component.

**Comment by tibeal** [comment]
Fixed.

**Note**: if the program has details to be able to submit the invoice without items from the frontend the **_submit mode_** should be "Submit" instead of "Close"
