### ISSUE TITLE
Invoice Upload: Product Names are not being saved when added using New button

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#22]
Add products one at a time, using the New button. Fill all the required fields and submit the invoice.
Only the first product name is saved.
- Products selected for the invoice:
![image](https://user-images.githubusercontent.com/26011197/29473251-7174679a-842d-11e7-9f5c-9901e7503b54.png)
- Products saved:
![image](https://user-images.githubusercontent.com/26011197/29473300-a7069e6e-842d-11e7-8fb2-6e7ee12b4faa.png)

**Comment by tibeal** [comment]
This should be now fixed.
