### ISSUE TITLE
Invoice Upload: The Amount field indicates an invalid data when filled with a decimal value

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#24]
Although the invoice is correct saved, the Amount field sinalizes to member that it has an invalid data when filled with a decimal value.
- The page changes the field color and shows a validation message 
![image](https://user-images.githubusercontent.com/26011197/29475432-17392c3a-8436-11e7-964d-0996959db85d.png)
- But the invoice is correctly saved
![image](https://user-images.githubusercontent.com/26011197/29475412-002d822a-8436-11e7-8427-603512b24652.png)

**Comment by tibeal** [comment]
Fixed.
