### ISSUE TITLE
My Invoices - After pagination, invoices order changes

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#3]
When first loaded, the invoices displayed are the ones below:
![image](https://user-images.githubusercontent.com/26011197/27710178-2809d69e-5cf5-11e7-9b27-03b61f2ef862.png)
After pagination, when coming back to the first page, the invoices displayed are not all the same:
![image](https://user-images.githubusercontent.com/26011197/27710204-404edba0-5cf5-11e7-9850-5550ce3fb8fd.png)

**Comment by tibeal** [comment]
Fixed. now the order is kept. But there are still some issues like the "**undefined**" null fields and the Invoice Items Filter issue.
