### ISSUE TITLE
Invoice Upload - Amount field should not be displayed when invoice has no products

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#41]
If the Program is set to have items (Request Invoice Products = true) and the CMS is set to show no product fields (Has Details  = false), the Amount field should not be displayed.
The question is: hide the field in the javascript or let it be done by configuration (by not selecting the Amount field in the fieldset of the Invoice Record component).

**Comment by tibeal** [comment]
Done. The field will be removed based on the Program configuration.
