### ISSUE TITLE
Cannot approve invoice in the CMS Org

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloprp#6]
When trying to approve an invoice the message below is received:
![image](https://user-images.githubusercontent.com/26011197/27753606-ad5e189c-5dbc-11e7-855a-9bd9b1a45b70.png)

P.S.: In this example the invoice belongs to a program that does not request invoice authorization, and with a promotion set to give points to member when the invoice status changes to "Approved".

**Comment by tibeal** [comment]
Fixed. Please try again.

**Comment by mfernandagf** [comment]
The error message is still displayed.

**Comment by tibeal** [comment]
Same as:
#19
